In [108]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import sys
from matplotlib import font_manager, rc, cm                
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split


font_path = './font/GmarketSansTTFMedium.ttf'
font_name = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font_name)


In [116]:
df = pd.read_csv('./data/통합파일_군집.csv', index_col=0)
df
df.corr()

호당 매매가(천원)  호당 전세가(천원)   전세가율(%)  건축허가면적(m2)  지하철역 수(개)  \
호당 매매가(천원)         1.000000    0.961994 -0.824298   -0.242897   0.552059   
호당 전세가(천원)         0.961994    1.000000 -0.767979   -0.272988   0.544264   
전세가율(%)           -0.824298   -0.767979  1.000000    0.309727  -0.456130   
건축허가면적(m2)        -0.242897   -0.272988  0.309727    1.000000  -0.065677   
지하철역 수(개)          0.552059    0.544264 -0.456130   -0.065677   1.000000   
주민등록세대수(호)         0.083930    0.101997 -0.184876    0.452030   0.431167   
은행 점포수(개)          0.622294    0.642177 -0.428338    0.052383   0.721486   
1인가구(세대)           0.122866    0.133503 -0.217577    0.395444   0.436809   
아파트 매매거래 수        -0.315388   -0.296079  0.338761    0.628420  -0.044009   
아파트 입주예정 물량(세대)   -0.205109   -0.201310  0.179819    0.639674   0.038880   
직장인연봉(만원)         -0.016425    0.000642  0.005730   -0.151108  -0.062060   
직장인수(명)           -0.069431   -0.053050  0.042408    0.000518  -0.146881   
cluster           -0.337617   -0.253071 -0.011854   -0.121820  -0.285520   

                 주민등록세대수(호)  은행 점포수(개)  1인가구(세대)  아파트 매매거래 수  아파트 입주예정 물량(세대)  \
호당 매매가(천원)         0.083930   0.622294  0.122866   -0.315388        -0.205109   
호당 전세가(천원)         0.101997   0.642177  0.133503   -0.296079        -0.201310   
전세가율(%)           -0.184876  -0.428338 -0.217577    0.338761         0.179819   
건축허가면적(m2)         0.452030   0.052383  0.395444    0.628420         0.639674   
지하철역 수(개)          0.431167   0.721486  0.436809   -0.044009         0.038880   
주민등록세대수(호)         1.000000   0.345088  0.922132    0.528404         0.474394   
은행 점포수(개)          0.345088   1.000000  0.356754   -0.031942         0.052660   
1인가구(세대)           0.922132   0.356754  1.000000    0.342267         0.366597   
아파트 매매거래 수         0.528404  -0.031942  0.342267    1.000000         0.657755   
아파트 입주예정 물량(세대)    0.474394   0.052660  0.366597    0.657755         1.000000   
직장인연봉(만원)         -0.160775  -0.034992 -0.117716   -0.107891        -0.024503   
직장인수(명)           -0.071096  -0.109414 -0.104539    0.230768         0.085675   
cluster           -0.028714  -0.260662 -0.030825   -0.071061         0.010942   

                 직장인연봉(만원)   직장인수(명)   cluster  
호당 매매가(천원)       -0.016425 -0.069431 -0.337617  
호당 전세가(천원)        0.000642 -0.053050 -0.253071  
전세가율(%)           0.005730  0.042408 -0.011854  
건축허가면적(m2)       -0.151108  0.000518 -0.121820  
지하철역 수(개)        -0.062060 -0.146881 -0.285520  
주민등록세대수(호)       -0.160775 -0.071096 -0.028714  
은행 점포수(개)        -0.034992 -0.109414 -0.260662  
1인가구(세대)         -0.117716 -0.104539 -0.030825  
아파트 매매거래 수       -0.107891  0.230768 -0.071061  
아파트 입주예정 물량(세대)  -0.024503  0.085675  0.010942  
직장인연봉(만원)         1.000000  0.475211  0.088028  
직장인수(명)           0.475211  1.000000  0.068126  
cluster           0.088028  0.068126  1.000000

In [110]:
clu1 = df[(df['cluster'] == 0)]
clu2 = df[(df['cluster'] == 1)]
clu3 = df[(df['cluster'] == 2)]

In [113]:
# 통합 회귀분석

X = df[['건축허가면적(m2)','지하철역 수(개)','1인가구(세대)','아파트 매매거래 수','아파트 입주예정 물량(세대)','직장인연봉(만원)','직장인수(명)']]
Y = df['전세가율(%)']

# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15)
# print(X_train.shape)
# print(X_test.shape)

lr = LinearRegression()

lr.fit(X,Y)

r_square = lr.score(X, Y)
print(r_square)

print(lr.coef_)

print(lr.intercept_)

0.3747947280026924
[ 2.59953992e-06 -5.75182858e-01 -1.18499301e-04  1.55037563e-03
 -7.13668916e-05 -1.21694371e-05]
68.81502813860513


In [91]:
abs# cluster 1 회귀분석

X1 = clu1[['건축허가면적(m2)','지하철역 수(개)','주민등록세대수(호)','은행 점포수(개)']]
Y1 = clu1['호당 매매가(천원)']

# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15)
# print(X_train.shape)
# print(X_test.shape)

lr = LinearRegression()

lr.fit(X1,Y1)

r_square = lr.score(X1, Y1)
print(r_square)

print(lr.coef_)

print(lr.intercept_)

0.20439374012136724
[ 3.03866600e+02 -2.19443782e-02  2.07088296e+02]
62281.2810183892


In [99]:
# cluster 2 회귀분석

X2 = clu2[['건축허가면적(m2)','지하철역 수(개)','주민등록세대수(호)','은행 점포수(개)']]
Y2 = clu2['호당 매매가(천원)']

# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15)
# print(X_train.shape)
# print(X_test.shape)

lr = LinearRegression()

lr.fit(X2,Y2)

r_square = lr.score(X2, Y2)
print(r_square)

print(lr.coef_)

print(lr.intercept_)

0.6471212621371579
[ 9.79186616e-03  1.75284788e+03 -4.82576527e-01  3.06043826e+02]
164176.30680055168


In [101]:
# cluster 3 회귀분석

X3 = clu3[['건축허가면적(m2)','지하철역 수(개)','주민등록세대수(호)','은행 점포수(개)']]
Y3 = clu3['호당 매매가(천원)']

# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15)
# print(X_train.shape)
# print(X_test.shape)

lr = LinearRegression()

lr.fit(X3,Y3)

r_square = lr.score(X3, Y3)
print(r_square)

print(lr.coef_)

print(lr.intercept_)

0.4275116759100329
[-3.95473585e-03 -3.25199709e+02  1.13435366e-01 -5.37121443e+01]
24155.950433868573
